// 'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import HeaderComponent from "@/app/components/header/header";
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ecommerce-template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <HeaderComponent/>
          <div style={{marginTop: '7rem'}}>
            {children}
          </div>
      </body>
    </html>
  )
}
